### PR TITLE
[CIR] Just unwrap and visit the Expr for a CK_NoOp castexpr

### PR DESCRIPTION
**Pull request by lanza**
The following is hitting a default assert error due to unimplemented `NoOp`.
Simple map it here to unwrapping the child expr.

```
ReturnStmt 0x38fd38
`-ImplicitCastExpr 0x38fd20 'int' <LValueToRValue>
  `-ImplicitCastExpr 0x38fd08 'int' xvalue <NoOp>
    `-DeclRefExpr 0x38fce8 'int' lvalue ParmVar 0x38fae8 'i' 'int'
```

### CODE REVIEW

**Comment by bcardosolopes** [comment]
Lemme check whether I can reproduce this first, I don't think I ever got this AST on my end, are you working on a local rebase on top of master version of the repo?

**Comment by lanza** [comment]
> Lemme check whether I can reproduce this first, I don't think I ever got this AST on my end, are you working on a local rebase on top of master version of the repo?

Nope, just working directly on your branch.

**Comment by bcardosolopes** [comment]
> ```
> ReturnStmt 0x38fd38
> `-ImplicitCastExpr 0x38fd20 'int' <LValueToRValue>
>   `-ImplicitCastExpr 0x38fd08 'int' xvalue <NoOp>
>     `-DeclRefExpr 0x38fce8 'int' lvalue ParmVar 0x38fae8 'i' 'int'
> ```

This is looking like malformed AST to me, the second level of ImplicitCastExpr is odd, doesn't make sense, should be a direct parent of DeclRefExpr in `types.c`. This is what I get:
```
/home/brunolopes/Dev/compilers/clangir/Build+Release+Libcxx+Assert/bin/clang -cc1 -x c++ -std=c++20 -internal-isystem /home/brunolopes/Dev/compilers/clangir/Build+Release+Libcxx+Assert/lib/clang/14.0.0/include -nostdsysteminc -triple x86_64-unknown-linux-gnu  /home/brunolopes/Dev/compilers/clangir/clang/test/CIR/CodeGen/types.c -fsyntax-only -ast-dump
...
`-FunctionDecl 0x7e150d8 </home/brunolopes/Dev/compilers/clangir/clang/test/CIR/CodeGen/types.c:6:1, col:27> col:5 t0 'int (int)'
  |-ParmVarDecl 0x7e14fe8 <col:8, col:12> col:12 used i 'int'
  `-CompoundStmt 0x7e15230 <col:15, col:27>
    `-ReturnStmt 0x7e15220 <col:17, col:24>
      `-ImplicitCastExpr 0x7e15208 <col:24> 'int' <LValueToRValue>
        `-DeclRefExpr 0x7e151e8 <col:24> 'int' lvalue ParmVar 0x7e14fe8 'i' 'int'
```

I've tested against c++11 c++14 c++17 c++20 just to double check I wasn't missing some specific language setup.

**Comment by lanza** [comment]
Ahhhhhhh I figured it out, I had been playing with `set(CLANG_DEFAULT_STD_CXX cxx2b)` and had it checked into one of my cmake cache files...

**Pull request closed without merging**
